version: "3.8"

services:
  nextjs:
    ports:
      - 4006:4006
    container_name: frontend
    image: frontend:latest
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile  
    environment:
      ANALYZE: false
